#!/bin/bash

# Backend Services Start Script
# Run each service in a separate terminal

echo "🚀 Starting CyberSentinel Backend Services"
echo ""
echo "Run each service in a SEPARATE terminal:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 TERMINAL 1 - Auth Service (Port 8000):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd backend/auth-service"
echo "python -m venv venv"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo "uvicorn main:app --reload --port 8000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 TERMINAL 2 - ASM Service (Port 8001):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd backend/asm-service"
echo "python -m venv venv"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo "uvicorn main:app --reload --port 8001"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 TERMINAL 3 - VS Service (Port 8002):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd backend/vs-service"
echo "python -m venv venv"
echo "source venv/bin/activate"
echo "pip install -r requirements.txt"
echo "uvicorn main:app --reload --port 8002"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After starting, check:"
echo "   - Auth Service: http://localhost:8000/docs"
echo "   - ASM Service:  http://localhost:8001/docs"
echo "   - VS Service:   http://localhost:8002/docs"
echo ""

