"""initial

Revision ID: e79bfbe12d8c
Revises: 
Create Date: 2026-06-25 15:41:23.226482
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e79bfbe12d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_companies_owner_user_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('newsletter',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_email'), 'newsletter', ['email'], unique=False)
    op.create_index(op.f('ix_newsletter_service'), 'newsletter', ['service'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('asm_discoveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('domain', 'ip', 'cloud', 'repo', 'saas', 'user', name='asm_asset_type'), nullable=False),
    sa.Column('target_source', sa.Enum('FROM_ASSET', 'MANUAL_ENTRY', name='asm_target_source'), nullable=False),
    sa.Column('asset_ids', sa.JSON(), nullable=True),
    sa.Column('manual_targets', sa.JSON(), nullable=True),
    sa.Column('intensity', sa.Enum('LIGHT', 'NORMAL', 'DEEP', name='asm_intensity'), nullable=True),
    sa.Column('schedule_type', sa.Enum('QUICK', 'INTERVAL', 'CRON', name='asm_schedule_type'), nullable=True),
    sa.Column('schedule_value', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'PENDING', 'PAUSED', 'DELETED', 'FAILED', 'COMPLETED', name='asm_status'), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asm_discoveries_org_id'), 'asm_discoveries', ['org_id'], unique=False)
    op.create_table('member_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('supabase_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'supabase_user_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_member_profiles_email'), 'member_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_member_profiles_org_id'), 'member_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_member_profiles_supabase_user_id'), 'member_profiles', ['supabase_user_id'], unique=False)
    op.create_table('member_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('supabase_user_id', sa.String(), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'supabase_user_id', name='uq_org_member_settings')
    )
    op.create_index(op.f('ix_member_settings_org_id'), 'member_settings', ['org_id'], unique=False)
    op.create_index(op.f('ix_member_settings_supabase_user_id'), 'member_settings', ['supabase_user_id'], unique=False)
    op.create_table('org_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_invites_email'), 'org_invites', ['email'], unique=False)
    op.create_index(op.f('ix_org_invites_org_id'), 'org_invites', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_invites_token'), 'org_invites', ['token'], unique=True)
    op.create_table('team_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('asm_admin_endpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('subdomain_id', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('endpoint_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asm_discovery_id', 'url', name='uq_admin_endpoint')
    )
    op.create_index(op.f('ix_asm_admin_endpoints_asm_discovery_id'), 'asm_admin_endpoints', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_admin_endpoints_asset_id'), 'asm_admin_endpoints', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_admin_endpoints_org_id'), 'asm_admin_endpoints', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_admin_endpoints_subdomain_id'), 'asm_admin_endpoints', ['subdomain_id'], unique=False)
    op.create_index(op.f('ix_asm_admin_endpoints_url'), 'asm_admin_endpoints', ['url'], unique=False)
    op.create_table('asm_api_endpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('subdomain_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('endpoint_type', sa.String(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asm_discovery_id', 'url', name='uq_endpoint_per_discovery')
    )
    op.create_index(op.f('ix_asm_api_endpoints_asm_discovery_id'), 'asm_api_endpoints', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_api_endpoints_asset_id'), 'asm_api_endpoints', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_api_endpoints_org_id'), 'asm_api_endpoints', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_api_endpoints_subdomain_id'), 'asm_api_endpoints', ['subdomain_id'], unique=False)
    op.create_index(op.f('ix_asm_api_endpoints_url'), 'asm_api_endpoints', ['url'], unique=False)
    op.create_table('asm_backup_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('subdomain_id', sa.String(), nullable=True),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asm_discovery_id', 'file_url', name='uq_backup_file')
    )
    op.create_index(op.f('ix_asm_backup_files_asm_discovery_id'), 'asm_backup_files', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_backup_files_asset_id'), 'asm_backup_files', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_backup_files_file_url'), 'asm_backup_files', ['file_url'], unique=False)
    op.create_index(op.f('ix_asm_backup_files_org_id'), 'asm_backup_files', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_backup_files_subdomain_id'), 'asm_backup_files', ['subdomain_id'], unique=False)
    op.create_table('asm_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asm_changes_asset', 'asm_changes', ['asset_id'], unique=False)
    op.create_index('idx_asm_changes_discovery', 'asm_changes', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_changes_asm_discovery_id'), 'asm_changes', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_changes_asset_id'), 'asm_changes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_changes_org_id'), 'asm_changes', ['org_id'], unique=False)
    op.create_table('asm_cloud_resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('access_status', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asm_discovery_id', 'resource_name', name='uq_cloud_resource')
    )
    op.create_index(op.f('ix_asm_cloud_resources_asm_discovery_id'), 'asm_cloud_resources', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_cloud_resources_asset_id'), 'asm_cloud_resources', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_cloud_resources_org_id'), 'asm_cloud_resources', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_cloud_resources_resource_name'), 'asm_cloud_resources', ['resource_name'], unique=False)
    op.create_table('asm_discovery_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.Enum('UI', 'CRON', 'API', name='asm_trigger_source'), nullable=False),
    sa.Column('run_mode', sa.Enum('QUICK', 'SCHEDULED', name='asm_run_mode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='asm_run_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asm_discovery_runs_asm_discovery_id'), 'asm_discovery_runs', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_discovery_runs_org_id'), 'asm_discovery_runs', ['org_id'], unique=False)
    op.create_table('asm_ips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('subdomain_id', sa.String(), nullable=True),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exposure_score', sa.Integer(), nullable=True),
    sa.Column('exposure_level', sa.String(length=20), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('asn', sa.String(), nullable=True),
    sa.Column('asn_org', sa.String(), nullable=True),
    sa.Column('isp', sa.String(), nullable=True),
    sa.Column('owner_org', sa.String(), nullable=True),
    sa.Column('rdap_country', sa.String(), nullable=True),
    sa.Column('ptr_record', sa.String(), nullable=True),
    sa.Column('attribution_source', sa.String(), nullable=True),
    sa.Column('attribution_confidence', sa.Integer(), nullable=True),
    sa.Column('cloud_provider', sa.String(), nullable=True),
    sa.Column('is_cloud', sa.Boolean(), nullable=True),
    sa.Column('is_cdn', sa.Boolean(), nullable=True),
    sa.Column('cdn_provider', sa.String(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_duration_ms', sa.Integer(), nullable=True),
    sa.Column('scan_metadata', sa.JSON(), nullable=True),
    sa.Column('score_explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'ip_address', 'subdomain_id', name='uq_ip_per_asset_subdomain')
    )
    op.create_index(op.f('ix_asm_ips_asm_discovery_id'), 'asm_ips', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_ips_asset_id'), 'asm_ips', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_ips_org_id'), 'asm_ips', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_ips_subdomain_id'), 'asm_ips', ['subdomain_id'], unique=False)
    op.create_table('asm_ports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('ip_id', sa.String(), nullable=True),
    sa.Column('subdomain_id', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('banner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'port', 'protocol', name='uq_port_per_ip')
    )
    op.create_index(op.f('ix_asm_ports_asm_discovery_id'), 'asm_ports', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_ports_asset_id'), 'asm_ports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_ports_ip_address'), 'asm_ports', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asm_ports_ip_id'), 'asm_ports', ['ip_id'], unique=False)
    op.create_index(op.f('ix_asm_ports_org_id'), 'asm_ports', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_ports_subdomain_id'), 'asm_ports', ['subdomain_id'], unique=False)
    op.create_table('asm_services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('ip_id', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'port', 'service_name', name='uq_service_per_port')
    )
    op.create_index(op.f('ix_asm_services_asm_discovery_id'), 'asm_services', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_services_asset_id'), 'asm_services', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_services_ip_address'), 'asm_services', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asm_services_ip_id'), 'asm_services', ['ip_id'], unique=False)
    op.create_index(op.f('ix_asm_services_org_id'), 'asm_services', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_services_port_id'), 'asm_services', ['port_id'], unique=False)
    op.create_table('asm_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asm_settings_user_id'), 'asm_settings', ['user_id'], unique=True)
    op.create_table('asm_ssl_certs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('subdomain_id', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('cipher', sa.String(), nullable=True),
    sa.Column('certificate_issuer', sa.String(), nullable=True),
    sa.Column('certificate_subject', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('certificate_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'port', name='uq_ssl_per_host')
    )
    op.create_index(op.f('ix_asm_ssl_certs_asm_discovery_id'), 'asm_ssl_certs', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_ssl_certs_asset_id'), 'asm_ssl_certs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_ssl_certs_host'), 'asm_ssl_certs', ['host'], unique=False)
    op.create_index(op.f('ix_asm_ssl_certs_org_id'), 'asm_ssl_certs', ['org_id'], unique=False)
    op.create_index(op.f('ix_asm_ssl_certs_subdomain_id'), 'asm_ssl_certs', ['subdomain_id'], unique=False)
    op.create_table('asm_subdomains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asm_discovery_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asm_discovery_id'], ['asm_discoveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'subdomain', name='uq_subdomain_per_asset')
    )
    op.create_index(op.f('ix_asm_subdomains_asm_discovery_id'), 'asm_subdomains', ['asm_discovery_id'], unique=False)
    op.create_index(op.f('ix_asm_subdomains_asset_id'), 'asm_subdomains', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asm_subdomains_org_id'), 'asm_subdomains', ['org_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('exposure', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_team_invites_email'), 'team_invites', ['email'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_team_invites_email'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asm_subdomains_org_id'), table_name='asm_subdomains')
    op.drop_index(op.f('ix_asm_subdomains_asset_id'), table_name='asm_subdomains')
    op.drop_index(op.f('ix_asm_subdomains_asm_discovery_id'), table_name='asm_subdomains')
    op.drop_table('asm_subdomains')
    op.drop_index(op.f('ix_asm_ssl_certs_subdomain_id'), table_name='asm_ssl_certs')
    op.drop_index(op.f('ix_asm_ssl_certs_org_id'), table_name='asm_ssl_certs')
    op.drop_index(op.f('ix_asm_ssl_certs_host'), table_name='asm_ssl_certs')
    op.drop_index(op.f('ix_asm_ssl_certs_asset_id'), table_name='asm_ssl_certs')
    op.drop_index(op.f('ix_asm_ssl_certs_asm_discovery_id'), table_name='asm_ssl_certs')
    op.drop_table('asm_ssl_certs')
    op.drop_index(op.f('ix_asm_settings_user_id'), table_name='asm_settings')
    op.drop_table('asm_settings')
    op.drop_index(op.f('ix_asm_services_port_id'), table_name='asm_services')
    op.drop_index(op.f('ix_asm_services_org_id'), table_name='asm_services')
    op.drop_index(op.f('ix_asm_services_ip_id'), table_name='asm_services')
    op.drop_index(op.f('ix_asm_services_ip_address'), table_name='asm_services')
    op.drop_index(op.f('ix_asm_services_asset_id'), table_name='asm_services')
    op.drop_index(op.f('ix_asm_services_asm_discovery_id'), table_name='asm_services')
    op.drop_table('asm_services')
    op.drop_index(op.f('ix_asm_ports_subdomain_id'), table_name='asm_ports')
    op.drop_index(op.f('ix_asm_ports_org_id'), table_name='asm_ports')
    op.drop_index(op.f('ix_asm_ports_ip_id'), table_name='asm_ports')
    op.drop_index(op.f('ix_asm_ports_ip_address'), table_name='asm_ports')
    op.drop_index(op.f('ix_asm_ports_asset_id'), table_name='asm_ports')
    op.drop_index(op.f('ix_asm_ports_asm_discovery_id'), table_name='asm_ports')
    op.drop_table('asm_ports')
    op.drop_index(op.f('ix_asm_ips_subdomain_id'), table_name='asm_ips')
    op.drop_index(op.f('ix_asm_ips_org_id'), table_name='asm_ips')
    op.drop_index(op.f('ix_asm_ips_asset_id'), table_name='asm_ips')
    op.drop_index(op.f('ix_asm_ips_asm_discovery_id'), table_name='asm_ips')
    op.drop_table('asm_ips')
    op.drop_index(op.f('ix_asm_discovery_runs_org_id'), table_name='asm_discovery_runs')
    op.drop_index(op.f('ix_asm_discovery_runs_asm_discovery_id'), table_name='asm_discovery_runs')
    op.drop_table('asm_discovery_runs')
    op.drop_index(op.f('ix_asm_cloud_resources_resource_name'), table_name='asm_cloud_resources')
    op.drop_index(op.f('ix_asm_cloud_resources_org_id'), table_name='asm_cloud_resources')
    op.drop_index(op.f('ix_asm_cloud_resources_asset_id'), table_name='asm_cloud_resources')
    op.drop_index(op.f('ix_asm_cloud_resources_asm_discovery_id'), table_name='asm_cloud_resources')
    op.drop_table('asm_cloud_resources')
    op.drop_index(op.f('ix_asm_changes_org_id'), table_name='asm_changes')
    op.drop_index(op.f('ix_asm_changes_asset_id'), table_name='asm_changes')
    op.drop_index(op.f('ix_asm_changes_asm_discovery_id'), table_name='asm_changes')
    op.drop_index('idx_asm_changes_discovery', table_name='asm_changes')
    op.drop_index('idx_asm_changes_asset', table_name='asm_changes')
    op.drop_table('asm_changes')
    op.drop_index(op.f('ix_asm_backup_files_subdomain_id'), table_name='asm_backup_files')
    op.drop_index(op.f('ix_asm_backup_files_org_id'), table_name='asm_backup_files')
    op.drop_index(op.f('ix_asm_backup_files_file_url'), table_name='asm_backup_files')
    op.drop_index(op.f('ix_asm_backup_files_asset_id'), table_name='asm_backup_files')
    op.drop_index(op.f('ix_asm_backup_files_asm_discovery_id'), table_name='asm_backup_files')
    op.drop_table('asm_backup_files')
    op.drop_index(op.f('ix_asm_api_endpoints_url'), table_name='asm_api_endpoints')
    op.drop_index(op.f('ix_asm_api_endpoints_subdomain_id'), table_name='asm_api_endpoints')
    op.drop_index(op.f('ix_asm_api_endpoints_org_id'), table_name='asm_api_endpoints')
    op.drop_index(op.f('ix_asm_api_endpoints_asset_id'), table_name='asm_api_endpoints')
    op.drop_index(op.f('ix_asm_api_endpoints_asm_discovery_id'), table_name='asm_api_endpoints')
    op.drop_table('asm_api_endpoints')
    op.drop_index(op.f('ix_asm_admin_endpoints_url'), table_name='asm_admin_endpoints')
    op.drop_index(op.f('ix_asm_admin_endpoints_subdomain_id'), table_name='asm_admin_endpoints')
    op.drop_index(op.f('ix_asm_admin_endpoints_org_id'), table_name='asm_admin_endpoints')
    op.drop_index(op.f('ix_asm_admin_endpoints_asset_id'), table_name='asm_admin_endpoints')
    op.drop_index(op.f('ix_asm_admin_endpoints_asm_discovery_id'), table_name='asm_admin_endpoints')
    op.drop_table('asm_admin_endpoints')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('team_roles')
    op.drop_index(op.f('ix_org_invites_token'), table_name='org_invites')
    op.drop_index(op.f('ix_org_invites_org_id'), table_name='org_invites')
    op.drop_index(op.f('ix_org_invites_email'), table_name='org_invites')
    op.drop_table('org_invites')
    op.drop_index(op.f('ix_member_settings_supabase_user_id'), table_name='member_settings')
    op.drop_index(op.f('ix_member_settings_org_id'), table_name='member_settings')
    op.drop_table('member_settings')
    op.drop_index(op.f('ix_member_profiles_supabase_user_id'), table_name='member_profiles')
    op.drop_index(op.f('ix_member_profiles_org_id'), table_name='member_profiles')
    op.drop_index(op.f('ix_member_profiles_email'), table_name='member_profiles')
    op.drop_table('member_profiles')
    op.drop_index(op.f('ix_asm_discoveries_org_id'), table_name='asm_discoveries')
    op.drop_table('asm_discoveries')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_newsletter_service'), table_name='newsletter')
    op.drop_index(op.f('ix_newsletter_email'), table_name='newsletter')
    op.drop_table('newsletter')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
