#!/usr/bin/env bash
#
# CyberSentinel — A-to-Z one-command local runner.
#
#   ./scripts/start.sh              full run: infra + deps + migrations + all app services
#   ./scripts/start.sh --no-infra   skip docker compose (infra already running elsewhere)
#   ./scripts/start.sh --skip-deps  skip venv/pip/npm install (faster restarts)
#   ./scripts/start.sh --skip-migrate  skip alembic upgrade
#   ./scripts/start.sh --infra-only    bring up postgres/redis/rabbitmq then exit
#   ./scripts/start.sh --down          stop infra containers and exit
#
# Does everything from scratch, in order:
#   1) preflight — check docker, python3, go, node/npm
#   2) generate any missing .env files with local-dev defaults
#   3) start infra (postgres:5432, redis:6379, rabbitmq:5672) and wait for health
#   4) create the API venv + pip install; frontend npm install (idempotent)
#   5) run Alembic migrations
#   6) launch all 5 app services with prefixed, colorised logs
#         api:8000 (/docs) · consumer · reporting · frontend:8080
#   Ctrl+C stops all app services (infra containers keep running; use --down to stop them).
#
set -uo pipefail
# Repo root is the parent of this script's dir (scripts/).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---- config ----------------------------------------------------------------
API_DIR="$ROOT/backend/api_service"
WORKERS_DIR="$ROOT/backend/workers"
FRONTEND_DIR="$ROOT/frontend"
REPORTING_DIR="$ROOT/backend/reporting"
VENV="$API_DIR/venv"
PY="$VENV/bin/python"
PIP="$VENV/bin/pip"
# Reporting needs all three on PYTHONPATH so both `backend.*` and `config.*`/`utils.*` resolve.
REPORT_PYTHONPATH="$ROOT:$ROOT/backend:$API_DIR"

# local-dev defaults (match docker-compose.yml: postgres/postgres, guest/guest, redis no auth)
PG_DSN_ASYNC="postgresql+asyncpg://postgres:postgres@localhost:5432/cybersentinel"
PG_DSN_GO="postgres://postgres:postgres@localhost:5432/cybersentinel?sslmode=disable"
REDIS_URL="redis://localhost:6379/0"
RABBIT_URL="amqp://guest:guest@localhost:5672/"
INTERNAL_TOKEN="dev-internal-token-change-me"

# flags
DO_INFRA=1; DO_DEPS=1; DO_MIGRATE=1; INFRA_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --no-infra)     DO_INFRA=0 ;;
    --skip-deps)    DO_DEPS=0 ;;
    --skip-migrate) DO_MIGRATE=0 ;;
    --infra-only)   INFRA_ONLY=1 ;;
    --down)         docker compose down; exit $? ;;
    -h|--help)      sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown flag: $arg (use --help)"; exit 2 ;;
  esac
done

# ---- pretty logging --------------------------------------------------------
c() { printf "\033[1;%sm%s\033[0m" "$1" "$2"; }        # c COLOR TEXT
step() { echo; echo "$(c 36 "▶ $1")"; }
ok()   { echo "  $(c 32 "✔") $1"; }
warn() { echo "  $(c 33 "⚠") $1"; }
die()  { echo "$(c 31 "[x] $1")" >&2; exit 1; }

# ---- 1) preflight ----------------------------------------------------------
step "1/6  Preflight — checking toolchain"
need() { command -v "$1" >/dev/null 2>&1 || die "missing '$1' — install it and re-run"; ok "$1 $("$1" --version 2>/dev/null | head -1)"; }
if [ "$DO_INFRA" = 1 ]; then need docker; fi
need python3; need go; need node; need npm

# ---- 2) env files ----------------------------------------------------------
step "2/6  Environment files"
gen_env() { # gen_env <path> <heredoc-var-name>
  local path="$1"
  if [ -f "$path" ]; then ok "$path exists"; return; fi
  warn "generating $path with local-dev defaults (fill in real SUPABASE_* values!)"
}

if [ ! -f "$API_DIR/.env" ]; then
  warn "creating backend/api_service/.env (SET YOUR SUPABASE VALUES)"
  cat > "$API_DIR/.env" <<EOF
# --- generated by scripts/start.sh — local dev defaults; replace SUPABASE_* with real values ---
DATABASE_URL=$PG_DSN_ASYNC
REDIS_URL=$REDIS_URL
RABBIT_URL=$RABBIT_URL
ASM_RABBIT_JOB_QUEUE=jobs.asm
CORS_ORIGINS_URL=http://localhost:8080
DEBUG=true
DB_AUTO_CREATE=true
TRUSTED_PROXY_HOPS=0
X_INTERNAL_TOKEN=$INTERNAL_TOKEN
# ---- REQUIRED: get these from your Supabase project settings ----
SUPABASE_URL=https://YOUR-PROJECT.supabase.co
SUPABASE_JWT_SECRET=replace-me
SUPABASE_WEBHOOK_SECRET=replace-me
EOF
else ok "backend/api_service/.env exists"; fi

if [ ! -f "$WORKERS_DIR/.env" ]; then
  warn "creating backend/workers/.env"
  cat > "$WORKERS_DIR/.env" <<EOF
# --- generated by scripts/start.sh — local dev defaults ---
DATABASE_URL=$PG_DSN_GO
REDIS_URL=$REDIS_URL
RABBIT_URL=$RABBIT_URL
ASM_RABBIT_JOB_QUEUE=jobs.asm
X_INTERNAL_TOKEN=$INTERNAL_TOKEN
JOB_MAX_CONCURRENCY=3
TASK_TIMEOUT_SECONDS=900
EOF
else ok "backend/workers/.env exists"; fi

if [ ! -f "$FRONTEND_DIR/.env" ]; then
  warn "creating frontend/.env (SET YOUR SUPABASE VALUES)"
  cat > "$FRONTEND_DIR/.env" <<EOF
# --- generated by scripts/start.sh — local dev defaults; replace VITE_SUPABASE_* ---
VITE_API_URL=http://localhost:8000
VITE_SUPABASE_URL=https://YOUR-PROJECT.supabase.co
VITE_SUPABASE_ANON_KEY=replace-me
EOF
else ok "frontend/.env exists"; fi

# ---- 3) infra --------------------------------------------------------------
if [ "$DO_INFRA" = 1 ]; then
  step "3/6  Infra — postgres, redis, rabbitmq"
  docker compose up -d postgres redis rabbitmq || die "docker compose failed"
  printf "  waiting for health"
  for i in $(seq 1 60); do
    healthy=$(docker compose ps --format '{{.Service}} {{.Health}}' 2>/dev/null \
              | grep -Ec 'postgres healthy|redis healthy|rabbitmq healthy')
    [ "${healthy:-0}" -ge 3 ] && { echo; ok "postgres + redis + rabbitmq healthy"; break; }
    printf "."; sleep 2
    [ "$i" = 60 ] && { echo; die "infra did not become healthy in 120s (check: docker compose logs)"; }
  done
else
  step "3/6  Infra — skipped (--no-infra); assuming 5432/6379/5672 are up"
fi

if [ "$INFRA_ONLY" = 1 ]; then ok "infra-only requested — done."; exit 0; fi

# ---- 4) dependencies -------------------------------------------------------
if [ "$DO_DEPS" = 1 ]; then
  step "4/6  Dependencies — python venv + frontend"
  if [ ! -x "$PY" ]; then
    python3 -m venv "$VENV" && ok "created venv"
  fi
  "$PIP" install -q --upgrade pip
  "$PIP" install -q -r "$API_DIR/requirements.txt" && ok "python deps installed"
  if [ ! -d "$FRONTEND_DIR/node_modules" ]; then
    ( cd "$FRONTEND_DIR" && npm ci ) && ok "frontend deps installed"
  else ok "frontend node_modules present (delete to reinstall)"; fi
else
  step "4/6  Dependencies — skipped (--skip-deps)"
  [ -x "$PY" ] || die "no venv at $VENV — run once without --skip-deps"
fi

# ---- 5) migrations ---------------------------------------------------------
if [ "$DO_MIGRATE" = 1 ]; then
  step "5/6  Database — alembic upgrade head"
  if ( cd "$API_DIR" && "$VENV/bin/alembic" upgrade head ); then
    ok "migrations applied"
  else
    warn "alembic failed — DB_AUTO_CREATE=true will create tables at API startup instead"
  fi
else
  step "5/6  Migrations — skipped (--skip-migrate)"
fi

# ---- 6) run all app services ----------------------------------------------
step "6/6  Launching services (Ctrl+C stops all)"
pids=()
cleanup() {
  echo; echo "$(c 36 "▶ stopping all app services…")"
  for p in "${pids[@]}"; do kill "$p" 2>/dev/null || true; done
  for p in "${pids[@]}"; do pkill -P "$p" 2>/dev/null || true; done
  wait 2>/dev/null || true
  echo "$(c 36 "▶ infra containers still running — './scripts/start.sh --down' to stop them")"
  exit 0
}
trap cleanup INT TERM

# run NAME COLOR -- <command...>   (prefixes each log line with [NAME])
run() {
  local name="$1" color="$2"; shift 3   # drop the literal '--'
  ( "$@" 2>&1 | while IFS= read -r line; do printf "\033[1;%sm[%s]\033[0m %s\n" "$color" "$name" "$line"; done ) &
  pids+=($!)
}

run api            34 -- bash -c "cd '$API_DIR' && '$VENV/bin/uvicorn' main:app --host 0.0.0.0 --port 8000 --reload"
run consumer       33 -- bash -c "cd '$WORKERS_DIR' && go run ./consumer/cmd/"
run reporting      32 -- bash -c "cd '$ROOT' && PYTHONPATH='$REPORT_PYTHONPATH' '$PY' backend/reporting/asm/main.py"
run frontend       36 -- bash -c "cd '$FRONTEND_DIR' && npm run dev"

echo
echo "$(c 32 "  api")        http://localhost:8000   (/docs for Swagger)"
echo "$(c 32 "  frontend")   http://localhost:8080"
echo "$(c 32 "  rabbitmq UI") http://localhost:15672 (guest/guest)"
echo
wait
